spring:
  web:
    resources:
      add-mappings: false # Disable static resource mapping (For NoHandlerFoundException)
  datasource:
    url: jdbc:mysql://localhost:3306/TelePigeon
    username: root
    password: 079381
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: localhost
      port: 6379