spring:
  web:
    resources:
      add-mappings: false # Disable static resource mapping (For NoHandlerFoundException)
  datasource:
    url: ${mysql_url}
    username: ${mysql_username}
    password: ${mysql_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: ${redis_host}
      port: ${redis_port}
    naver:
      clientId: ${naver_clientId}
      clientSecret: ${naver_clientSecret}
      url: ${naver_url}